---
title: "Subroutines (reporting templates)"
linkTitle: "Subroutines"
date: "`r Sys.Date()`"
description: "Subroutines perform part of an analysis and reporting algorithm."
weight: 102
categories: 
- Documentation
tags: 
- Software
- Software - executable
- Software - executable (subroutines)
output: hugodown::md_document
---

## What are subroutines?
Sub-routines need to be called by parent [programs](../programs) that supply them with input data. Sub-routines can be called by multiple programs and will produce output that varies based on the input values they are supplied with. They are typically deployed to implement parts of a model’s analysis and reporting algorithm.

## Why are they useful?
readyforwhatsnext model subroutines can be used primarily as templates to generate reports. They can be used in three ways:

- to help execute a program or function written by a third party (in which case you probably won't need to modify the subroutine and may not even be aware that it is being used);
- to help execute a program or function that you write (in which case, you shouldn't have to modify the subroutine, but may find it useful to customise it to your purposes); and
- to serve as a template for subroutines you write yourself that perform similar tasks (in which case you will be rewriting the subroutine's code).

## Current readyforwhatsnext subroutines
Currently available readyforwhatsnext subroutines are summarised in the below table.

````{=html}
```{r, echo=FALSE, message=F,results='asis'}
xfun::file_string('index_Body.html')
```
````

## Documentation
readyforhwhatsnext subroutines are currently minimally documented, typically in the form as notes contained in a README file in the source code bundle.

