---
title: "Finding programs"
linkTitle: "Find"
date: "`r Sys.Date()`"
description: "Programs are used to generate and report a model analysis."
weight: 3
categories: 
- Documentation
tags: 
- Software
- Software - executable
- Software - executable (programs)
output: hugodown::md_document
---

## What are programs?
Programs can be executed in their current form without the need for additional input data and, unless modified or run interactively (prompting a user for inputs during execution), will always generate the exact same output. They are typically deployed for configuring the run specifications of a computational model, specifying the data to which it will be applied and reporting analysis results. 

## Why are they used for in readyforwhatsnext?
readyforwhatsnext programs can be used for the following purposes:

- to reproduce a study analysis, in which case you will need access to the original study data, and may also need to modify the program to specify the path to this data from your machine;
- to replicate a study analysis (ie to apply the study algorithm to similar but different input data [this can be a new sample from the same population or, if used for demonstration purposes, fake data representative of the original study dataset]), in which case you will need to modify the program to specify the path to this data; and
- to transfer a study analysis, in which case you use the program as a template to be modified to reflect key differences between the original study and your study.

## Current readyforhwatsnext programs
Currently available readyforwhatsnext programs are summarised in the below table.

````{=html}
```{r, echo=FALSE, message=F,results='asis'}
xfun::file_string('index_Body.html')
```
````

## Documentation
readyforwhatsnext programs are typically self-documenting, meaning that each section of code is integrated with plain English descriptions of the purpose it fulfills. The only programs that are not self-documenting are those whose primary purpose is to produce a document (normally an analysis report). Self-documenting programs and sub-routines will be typically documented as a PDF or HTML render of the RMarkdown source file. This rendered document will be bundled with the program, but in some cases may also be shared in online data repositories.

